### ISSUE TITLE
Add Action to Disable a Product

### ISSUE THREAD

**Issue by Saikikusuo77** [CSCI-GA-2820-FA23-003/products#28]
**As a** manger of API
**I need** to be able to disable some product
**So that** they won't be sell to customers by accident 
   
 ### Details and Assumptions
 * Managers know the id of products that need to be disabled.
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given a product
 When manager disabled this product
 Then customer can not buy it
```

**Comment by Devank14** [comment]
Picked up.
