### ISSUE TITLE
Update a Product

### ISSUE THREAD

**Issue by sandyshao** [CSCI-GA-2820-FA23-003/products#5]
**As a product manager 
**I need the ability to update product info
**So that I can keep updated on products
   
 ### Details and Assumptions
 * Product can be looked up in database through unique key
 * Product attributes are easy to fetch and edit in database
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given product unique key
 When pass in product attributes that needs to be updated
 Then the database should show the latest/updated info about the product
```

**Comment by Saikikusuo77** [comment]
Hi, do you think only product manager can update the product will be better

**Comment by sandyshao** [comment]
> Hi, do you think only product manager can update the product will be better

Hey, from the slides, these are User Story, so my understanding is that the `As a`, `I need`, and ` So that` are from user's perspective, what they want to see/achieve.
