### ISSUE TITLE
Fix kubernetes

### ISSUE THREAD

**Issue by Saikikusuo77** [CSCI-GA-2820-FA23-003/products#66]
**As a** [role]
**I need** [function]  
**So that** [benefit]  
   
 ### Details and Assumptions
 * [document what you know]
   
 ### Acceptance Criteria  
   
 ```gherkin
 Given [some context]
 When [action taken]
 Then [outcome observed]
```

**Comment by jalam7** [comment]
This bug is fixed, please close this issue.
